---
title: "\"NERC training stuff\""
subtitle: "Teaching environmental scientists how to escape from Excel"
author: 
    name: Chris Wood
    affiliation: EPCC, University of Edinburgh
    email: c.wood@epcc.ed.ac.uk
format:
  revealjs: 
    template-partials:
      - title-slide.html
    slide-number: false
    preview-links: false
    logo: logo.png
    smaller: true

    # css: styles.css
    theme: [serif, custom.scss]
    footer: 'ESCES overview presentation'
    center: false
    embed-resources: true
---

## How it started

::: {.fragment}
 - NERC ASTC calls
    - Relatively small amounts of funding to run relevant training courses for NERC-domain researchers (max of £60k per submission)
    - Most funded bids are for single, high-cost, summer-school-style courses
    - We realised there was a gap in courses covering scientific computing skills 
:::

::: {.fragment}
 - Essential Scientific Computing Skills for Environmental Scientists (ESCES) was born:
    - Training for non-computational environmental and life scientists
    - Fills a skills gap that UKRI has acknowledged for several years exists
    - Build upon the well tested material of The Carpentries 
      - Fork the lessons and modify many of the examples to make them more environmental focussed: try to reduce cognitive load 
:::

::: {.notes}
Conveniently been asked to talk about this separately in a couple of weeks, good reuse of presentation! :)
:::

## ESCES (1)

::: {.fragment}
  - June 2022 - May 2023
  - Carpentries material forked and modifed
  - 6 courses planned:
    - 2 each of a "beginner" (Bash, Python & Numpy, git) and "intermediate" (more Bash, "Python best practices", data analysis using Pandas) course
:::

::: {.fragment}
- funding for travel and accommodation so that PhD students don't need to use their RTSG
    - these kinds of skills *are* important, but not as important as attending a conference or buying lab consumables...  
  - ring-fenced budget for DEI
  - 180 places; 232 registrations 
  - panel score: 7
:::

::: {.notes}
assuming knowledge of Python when teaching Pandas means we can cover more material, including a brand new geospatial episode we wrote specifically
caring: e.g. paying for caring so parents can attend full day courses they might not otherwise be able to
:::

## It continued: ESCES2

::: {.fragment}
 
 - August 2023 - July 2024
 - introduced an advanced course covering distributed data analysis using Spark on JASMIN, basic parallelisation using GNU Parallel and numba
 - expanded courses to three locations (added Liverpool); 4 beginner courses; 3 intermediate courses; 2 advanced courses
 - 3 "bring your own data" days (one at each level, in each location) <!-- [but, had an underspend so added an extra BYOD day to final in-person course] -->
 - 240 total places across all 9 courses (limit because of ~~bug~~ _feature_ in Je-S Studentship Application form...); 433 registrations
 - panel score: 8
:::

## ...and again: ESCES3

::: {.fragment}

 - April 2025 - April 2026 
 - basically a repeat of ESCES2
 - intermediate online course was run as over 4 half day sessions
 - advanced in-person course is ~200% oversubscribed
 - 240 total places across all 9 courses; 308 registrations to date (6 courses done so far)
 - panel score: 9
:::

::: {.notes}
intermediate course: (Monday; Tuesday; Monday; Tuesday) with a later start; seems to have been well received; less intense for both instuctors and learners
advanced course over-subscription: we have enough underspend that we're intending to run another course
:::

## Success?

::: {.fragment}
- Panel scores increased for each grant; feedback was generally very positive
- Attendees are encouraged to complete the Carpentries pre- and post-workshop surveys for each course
  - allows us to get some metrics that The Carpenties calculates, including NPS (-100<NPS<+100; a good course is >50; an excellent course is >75)
  - we have had one course that was 92(!); all courses above 50
:::

::: {.fragment}
- we also ask them to complete "post-it note feedback" and a more generic very short post-course survey
- Significant number of attendees return (55 attendees of a novice course have signed up to an intermediate course)
- panel only funded one computational training course in 2025/6 (in previous rounds University of Manchester had funding to run Intermediate Software Development; they were unsucessful this year)
:::

## What attendees have said about the courses

Since I'm quiet and unassuming, and not at all narcissistic, this is the _most_ modest feedback... :) 

::: {.fragment}

 > It was a wonderful course! Really enjoy it! I learned a lot-Thank you sooo much
 
 > I've learned more than I ever have, thank you!
 
 > Andrew is a great teacher. Really good at the conceptual framework stuff. Analogies and diagrams v. useful

 > Geospatial -> interactive maps will be SUPER useful for my data! Was really interesting!
:::

##

 > Great content :) It is nice to learn the 'official' way of doing things instead of my dodgy stack overflow accumulated knowledge. Also good to know why things are the way they are. I now want to go and streamline my code to tidy it up and be nicer
 
 > courses taught by both Andrew & Chris was great and they were both very interactive. Nice experience :) Thank you!

 > Very good instructions and the help from the PhD students was great

 > Chris is really passionate & very good in teaching the python code. The lecture is really helpful and useful

 > This course is great! I always thought supercomputers were hard + not for me

 - plenty of constructive criticism too (mainly around setup issues, not enough time doing exercises, speed [too fast *and* too slow])

::: {.notes}
and misunderstandings over files location in jupyter vs windows - how to start a notebook in a specific location, etc - especially for beginners
:::

## Some thoughts

::: {.fragment}
 - wide range of organisations represented by attendees, including public sector (e.g. SEPA, UKHO) and NGO (e.g. National Trust)
   - wouldn't normally have access to this kind of course
 - can never please everyone! Even with making examples environmental some feedback was they didn't understand the context
:::

::: {.fragment}
 - conversion of initial registrations to attendee is only ~50%
 - good retention rate for courses, even for online
:::

::: {.fragment}
 - these grants give 100% cash value (including staff costs) rather than 80% fEC
 - compared with other ASTC courses still seems very good value per attendee
 - future funding opportunities? ASTC seems to have been quietly dropped for now
 - potential bigger collaboration with University of Manchester
 - I've been doing all admin + sorting out registrations, which has been fairly time consuming for nearly 1000 registrations...
:::

::: {.notes}
content: even within env sciences there's a very wide range: people doing ecology might not understand the ocean wave data we use, but will never win...
mix of these leads to the underspend we get each year
in reality these are about equivalent but there are still extra admin hurdles to jump through
I submitted a bid for a similar STFC grant but wasn't successful
:::

## tl;dr

(if you've been reading your emails for the last 10 mins)

  - 3 years of NERC training: total of £156,745
  - reduce cognitive load by using datasets and examples from the environmental sciences
  - beginner, intermediate, and advanced courses - most of which built on existing Carpentries material (a mix of Bash, Python, git)
  - 24 courses
    - 660 places
    - 973 registrants 
    - 480 actual attendees to date
  - well received by attendees and ASTC review panels
  - future courses dependent on some sort of funding

## Acknowledgements

Lots!

::: {.fragment}
Co-Is:

 - Neil Chue Hong (EPCC) [ESCES1 & 2]
 - Daniel Barker (School of Biological Sciences, University of Edinburgh)
 - Lucy Bricheno (National Oceanography Centre) \[ESCES1]
 - Andrew Walker (Department of Earth Sciences, University of Oxford) [ESCES2 & 3]
 - Colin Sauze (National Oceanography Centre) [ESCES2 & 3]
 - Tobias Ferreira (National Oceanography Centre) [ESCES3]
:::

::: {.fragment}
Other instructors:

 - Kashyap Chhatbar, Tony Hallam, Ruairidh MacLeod
:::

## Even more acknowledgements

::: {.fragment}
 - EPCC admin and finance
:::

::: {.fragment}
Lots and lots of demonstrators (apologies to any I've missed!):

- Flic Anderson, Jakub Adamski, David Katz, Ananya Gangopadhyay, Cathal MacStay, Jake Davies, Gabriel Rodríguez Canal, Ricardo Jesus, Simon Harnqvist, Eddie Martin, Rebecca Colquhoun, Tobermory Mackay-Champion, Hannah Sanderson, Martyn Steel, George Perera, Auggie Marignier, Ken Smith, Max Birkett, Ian Smith, Justin Leung, Biao Wang, Adrian Mag, Zihao Chen, Adam Harding, Viktoria Trautner, Dan Gittins, Louis Headley, Xingran Ruan, Franck Latallerie
:::

## Thanks!

 🔗 All course material:  https://github.com/nerc-esces

[**Funding**:]{.smallcaps}

  - ESCES (NE/Y003799/1)
  - ESCES2 (NE/X009211/1)
  - ESCES3 (UKRI1308)

[**Contact**:]{.smallcaps} c.wood@epcc.ed.ac.uk